### ISSUE TITLE
App Crash v1.1.1 - normalize() function returns NaN

### ISSUE THREAD

**Issue by bam-e22** [lincollincol/compose-audiowaveform#14]
App crashes when using silent audio source 
ex) amplitudes = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```
java.lang.IllegalStateException: AnimationVector cannot contain a NaN. AnimationVector1D: value = NaN. Animation: TargetBasedAnimation: 1.0 -> NaN,initial velocity: AnimationVector1D: value = 0.0, duration: 500 ms,animationSpec: androidx.compose.animation.core.VectorizedTweenSpec@64fbf4d, playTimeNanos: 0
    at androidx.compose.animation.core.TargetBasedAnimation.getValueFromNanos(Animation.kt:242)
    at androidx.compose.animation.core.SuspendAnimationKt.animate(SuspendAnimation.kt:233)
    at androidx.compose.animation.core.Animatable$runAnimation$2.invokeSuspend(Animatable.kt:305)
    at androidx.compose.animation.core.Animatable$runAnimation$2.invoke(Unknown Source:8)
    at androidx.compose.animation.core.Animatable$runAnimation$2.invoke(Unknown Source:2)
    at androidx.compose.animation.core.MutatorMutex$mutate$2.invokeSuspend(InternalMutatorMutex.kt:119)
    at androidx.compose.animation.core.MutatorMutex$mutate$2.invoke(Unknown Source:8)
    at androidx.compose.animation.core.MutatorMutex$mutate$2.invoke(Unknown Source:4)
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
    at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
    at androidx.compose.animation.core.MutatorMutex.mutate(InternalMutatorMutex.kt:112)
    at androidx.compose.animation.core.MutatorMutex.mutate$default(InternalMutatorMutex.kt:109)
    at androidx.compose.animation.core.Animatable.runAnimation(Animatable.kt:295)
    at androidx.compose.animation.core.Animatable.animateTo(Animatable.kt:238)
    at androidx.compose.animation.core.Animatable.animateTo$default(Animatable.kt:225)
    at androidx.compose.animation.core.AnimateAsStateKt$animateValueAsState$3$1.invokeSuspend(AnimateAsState.kt:428)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
    at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
    at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7872)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by divyanshdxn** [comment]
The issue is when minHeight = maxHeight, the diff becomes 0 and div by zero returns NaN, see [#L47](https://github.com/lincollincol/compose-audiowaveform/blob/master/audiowaveform/src/main/java/com/linc/audiowaveform/AudioWaveform.kt#L147)

**Comment by divyanshdxn** [comment]
For now I'm just using a workaround `normalize(minHeight, maxHeight).map { if (it.isNaN()) 0f else it }`

**Comment by Xing1P** [comment]
I face this issue too

**Comment by thedroiddiv** [comment]
@Xing1P for now you can try this fix
https://github.com/lincollincol/compose-audiowaveform/pull/20/files

**Comment by thedroiddiv** [comment]
@lincollincol just a friendly reminder. If you're free, please have a look at #20

**Comment by CoderBDK** [comment]
**Problem:**
I encountered the same issue where NaN values were causing the animation to crash, even after applying the proposed fix.

**What I Tried:**
I used the fix shared earlier to handle division by zero, but it still caused crashes in my case.

**Solution I Used:**
I simplified the fix to directly replace any NaN values with a fallback value (such as `MinSpikeHeight`) before passing them into the animation state. Here’s the solution I applied:

```kotlin
val spikesAmplitudes = remember(amplitudes, spikes, amplitudeType) {
    amplitudes.toDrawableAmplitudes(
        amplitudeType = amplitudeType,
        spikes = spikes.toInt(),
        minHeight = MinSpikeHeight,
        maxHeight = canvasSize.height.coerceAtLeast(MinSpikeHeight)
    )
}.map {
    animateFloatAsState(
        it.takeIf { !it.isNaN() } ?: MinSpikeHeight,  // Replacing NaN with MinSpikeHeight
        spikeAnimationSpec
    ).value
}
```

**Comment by ppawaraxxess** [comment]
I'm seeing a similar crash on the latest build. I'm using the audio waveform to depict live recording. The crash happens when there's no active audio / silence in the room. Any help or suggestions are appreciated.

java.lang.IllegalStateException: AnimationVector cannot contain a NaN. AnimationVector1D: value = NaN. Animation: TargetBasedAnimation: 1.0 -> NaN,initial velocity: AnimationVector1D: value = 0.0, duration: 500 ms,animationSpec: androidx.compose.animation.core.VectorizedTweenSpec@5348c4d, playTimeNanos: 0
at androidx.compose.animation.core.PreconditionsKt.throwIllegalStateException(Preconditions.kt:41)
                                                                                                    	at androidx.compose.animation.core.TargetBasedAnimation.getValueFromNanos(Animation.kt:499)
                                                                                                    	at androidx.compose.animation.core.SuspendAnimationKt.animate(SuspendAnimation.kt:225)
                                                                                                    	at androidx.compose.animation.core.Animatable$runAnimation$2.invokeSuspend(Animatable.kt:308)
                                                                                                    	at androidx.compose.animation.core.Animatable$runAnimation$2.invoke(Unknown Source:8)
                                                                                                    	at androidx.compose.animation.core.Animatable$runAnimation$2.invoke(Unknown Source:2)
                                                                                                    	at androidx.compose.animation.core.MutatorMutex$mutate$2.invokeSuspend(InternalMutatorMutex.kt:126)
                                                                                                    	at androidx.compose.animation.core.MutatorMutex$mutate$2.invoke(Unknown Source:8)
                                                                                                    	at androidx.compose.animation.core.MutatorMutex$mutate$2.invoke(Unknown Source:4)
                                                                                                    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:42)
                                                                                                    	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)
                                                                                                    	at androidx.compose.animation.core.MutatorMutex.mutate(InternalMutatorMutex.kt:119)
                                                                                                    	at androidx.compose.animation.core.MutatorMutex.mutate$default(InternalMutatorMutex.kt:116)
                                                                                                    	at androidx.compose.animation.core.Animatable.runAnimation(Animatable.kt:299)
                                                                                                    	at androidx.compose.animation.core.Animatable.animateTo(Animatable.kt:241)
                                                                                                    	at androidx.compose.animation.core.Animatable.animateTo$default(Animatable.kt:227)
                                                                                                    	at androidx.compose.animation.core.AnimateAsStateKt$animateValueAsState$3$1$1.invokeSuspend(AnimateAsState.kt:427)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:79)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8762)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@cc60b91, androidx.compose.runtime.BroadcastFrameClock@aff4af6, androidx.compose.runtime.LaunchedEffectImpl@3e84c7f, StandaloneCoroutine{Cancelling}@7ce0ef7, AndroidUiDispatcher@555d164]

**Comment by thedroiddiv** [comment]
@ppawaraxxess Can you share the piece of code how you're using the amp values?
